name: inventorymanagement

services:
  postgres:
    container_name: inventory-management-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    networks: [eim]
    ports: ["5432:5432"]
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

networks:
  eim:
    name: eim

volumes:
  postgres-data:
