name: dotnetbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Install PostgreSQL Client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h ${{ secrets.DB_HOST }} -p 5432 -U ${{ secrets.DB_USER }}; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL is ready!"

    - name: Run SQL Scripts (Initialize and Seed DB)
      env:
        PGHOST: ${{ secrets.DB_HOST }}
        PGPORT: 5432
        PGUSER: ${{ secrets.DB_USER }}
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        PGDATABASE: ${{ secrets.DB_NAME }}
      run: |
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -f sql_scripts/init_database.sql
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -f sql_scripts/seed_database.sql

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
