# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnetbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Start container and apply migrations
      run: docker compose -f "Docker-compose.yml" up -d --build
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          if docker exec $(docker ps -qf "name=postgres") pg_isready -U postgres; then
            echo "PostgreSQL is ready"
            exit 0
          fi
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL failed to start"
        exit 1
    - name: Run EF Core Migrations
      run: docker compose -f "Docker-compose.yml" run --rm app
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
    - name: Stop containers
      run: docker compose -f "Docker-compose.yml" down --remove-orphans --rmi all --volumes
